### PR TITLE
#1264 fix ampersand parsing bug

### PR DESCRIPTION
**Pull request by tomakita**
Fix for https://github.com/fsharp/FSharp.Data/issues/1264

When parsing HTML, the HTML string is accessed via a TextReader.  When the parser encountered a '&' that wasn't part of a HTML entity (e.g. "&quot;"), it would scan to the end of the TextReader, but it wouldn't detect when it had reached the end of the TextReader, so it would repeatedly append the '\uffff' character to the end of the parsing output.  '\uffff' is the character you get if you cast -1 to char.  -1 is the value that TextReader returns when a client has reached the end of the TextReader.

Let me know if there are problems with the way I've approached this, or if there are any improvements that could be made.  Thanks for taking a look!

@colinbull

### CODE REVIEW

**Comment by colinbull** [comment]
@tomakita Thanks for this.  Could you give me access to push to your branch https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork I have some changes to add. Before merge.

**Comment by tomakita** [comment]
@colinbull Sure, I think you should be able to add changes -- I've checked the "Allow edits from maintainers" checkbox.  Let me know if you don't have access.

**Comment by colinbull** [comment]
@tomakita Thanks done.

**Comment by dsyme** [comment]
@colinbull is this ready?

**Comment by njlr** [comment]
It looks like the CI failed due to an HTTP request in a test failing. Can it be kicked again?

**Comment by dsyme** [comment]
Closing this out due to repo divergence.  Please resubmit if you'd like to merge it with main

**Pull request closed without merging**
