### PR TITLE
Update fsdocs

### PR DESCRIPTION
**Pull request by nojaf**
Hi there, I've been working on a new theme for [FSharp.Formatting](https://github.com/fsprojects/FSharp.Formatting/issues/849).
I would like to start rolling out the latest alpha and gather some real-world feedback.

Other examples:
- https://ionide.io/FSharp.Analyzers.SDK/
- https://ionide.io/ionide-analyzers/
- https://fsprojects.github.io/FsLexYacc/

Thanks for considering this PR!

### CODE REVIEW

**Comment by Thorium** [comment]
This PR seems to pass CI and current master doesn't.

**Comment by nojaf** [comment]
Yes, I believe master doesn't have the fix of https://github.com/fsprojects/FSharp.Data/pull/1496/commits/dc356ce12a7ff24203074849cafd6ac9cdd8f94f

**Review by cartermp — APPROVED** [review]
Hmmm, `main` passed the last time I touched it for a release. But regardless, if it's green here then it should be green for docs too.

**Comment by nojaf** [comment]
Not sure what went wrong in https://github.com/fsprojects/FSharp.Data/actions/runs/6855774344/job/18641541374

This works on my local Windows machine.

**Comment by Thorium** [comment]
I merged the main to my 4 PRs and 2 passed, 2 failed. They all pass in my machine. So this is a random failure.

**Comment by Thorium** [comment]
It seems to me that it's a network error in WorldBank provider. Not sure why unit tests are doing network requests.

**Comment by cartermp** [comment]
This should be live now: https://fsprojects.github.io/FSharp.Data/library/XmlProvider.html

**Comment by nojaf** [comment]
Yes, thank you!

**Comment by Thorium** [comment]
The current 6.4.0 release build didn't create a NuGet package, because build failed after spending about 6 hours in the document generation phase:

> GenerateDocs   05:57:06.9700490   (Failed to generate docs)

Details: https://github.com/fsprojects/FSharp.Data/actions/runs/8258675234/job/22591313017#step:6:1764

**Comment by nojaf** [comment]
Mildly interesting, you could try and update to v20 stable and see if that helps.

**Pull request merged**
