### PR TITLE
New functions that would allow Markdown Tables

### PR DESCRIPTION
**Pull request by xdaDaveShaw**
Implementation of #1238 

Two new options on the `CsvProvider` type:

- `IgnoreLinePattern`: A regular expression for lines to ignore.
- `TrimColumnValue`: Whether the values in a column should be trimmed.

### CODE REVIEW

**Comment by xdaDaveShaw** [comment]
This is my first PR to this repo and is also my first work on Type Providers - and it is only an idea - so feel free to reject it, or ask for improvements.

**Comment by dsyme** [comment]
Close/open to re-run CI

**Comment by xdaDaveShaw** [comment]
Looks like I need to fix some things - will take a look tonight if I have time

**Comment by dsyme** [comment]
@xdaDaveShaw Apologies for the late reply.

This is interesting - though should there be a separate "MarkdownProvider"?   It seems odd to include this as part of CSV.

**Comment by xdaDaveShaw** [comment]
@dsyme - I was only referring to Markdown Tables - not all of Markdown - that might be more of a challenge.

The have an "almost" CSV like format, if only the header/rows separator could be ignored, and values trimmed to fix the type inference. 

e.g. 

```
|Col1|Col2|
|----|----|      <- Skipping this...
|1   |str |
  ^^^            <- trimming this
```

I don't mind this been rejected if there are no other uses for the feature and Markdown would be better served elsewhere.

**Comment by dsyme** [comment]
Closing this out due to repo divergence.  Please resubmit if you'd like to

**Pull request closed without merging**
