### PR TITLE
Inline schemas docs

### PR DESCRIPTION
**Pull request by mlaily**
As a follow up PR for #1447, here is some documentation about the feature!

The branch is currently on top of the previous PR branch.  
Please ignore all but the last two commits until the previous PR is merged and this one is rebased.

Note the TODO in the latest commit: I'm not sure which version will contain this new feature, so I left a `version TBD` that will have to be replaced before we merge the docs.

### CODE REVIEW

**Comment by cartermp** [comment]
@mlaily I merged the other one, could you rebase this please?

**Comment by mlaily** [comment]
@cartermp done.

**Comment by mlaily** [comment]
@cartermp but be careful not to merge this as-is: there is still a TODO to fix (replace a "version TBD" with the expected next version number)

**Comment by cartermp** [comment]
@mlaily there's a new version out - 4.2.10 - could you add that as appropriate here?

(also I now realize this could have been a 4.3 release, ah well)

**Comment by mlaily** [comment]
Ha, so much for semantic versioning! :D

I replaced the version TBD with 4.2.10, updated the commit message, and rebased!

Thank you for your work :)

**Comment by cartermp** [comment]
We live dangerously.

**Review by cartermp — APPROVED** [review]

**Pull request merged**
